In [3]:
import pandas as pd
from sqlalchemy import create_engine


### Transform Delay DataFrame

In [4]:
#importing files 
delay_2008 = "Resources/2008.csv"
delay_df = pd.read_csv(delay_2008)
delay_df.tail()

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
7009723,2008,12,13,6,1002.0,959,1204.0,1150,DL,1636,...,6.0,45.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
7009724,2008,12,13,6,834.0,835,1021.0,1023,DL,1637,...,5.0,23.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
7009725,2008,12,13,6,655.0,700,856.0,856,DL,1638,...,24.0,12.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
7009726,2008,12,13,6,1251.0,1240,1446.0,1437,DL,1639,...,13.0,13.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
7009727,2008,12,13,6,1110.0,1103,1413.0,1418,DL,1641,...,8.0,11.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN

In [5]:
# Create a filtered dataframe from specific columns
delay_cols = ["FlightNum", "UniqueCarrier", "Year", "Month", "DayOfWeek"]
delay_transformed = delay_df[delay_cols].copy()

# Rename the column headers
delay_transformed = delay_transformed.rename(columns={"FlightNum": "id",
                                                          "UniqueCarrier": "unique_carrier",
                                                          "Year": "year",
                                                     "Month": "month",
                                                     "DayOfWeek": "week_day"})

# Clean the data by dropping duplicates and setting the index
delay_transformed.drop_duplicates("id", inplace=True)
delay_transformed.set_index("id", inplace=True)

delay_transformed.head()

     unique_carrier  year  month  week_day
id
335              WN  2008      1         4
3231             WN  2008      1         4
448              WN  2008      1         4
1746             WN  2008      1         4
3920             WN  2008      1         4

### Transform Landing DataFrame

In [43]:
#importing files 
landings_file = "Resources/air-traffic-landings-statistics.csv"
landings_df = pd.read_csv(landings_file)
landings_df.head()

,Activity Period,Operating Airline,Operating Airline IATA Code,Published Airline,Published Airline IATA Code,GEO Summary,GEO Region,Landing Aircraft Type,Aircraft Body Type,Aircraft Manufacturer,Aircraft Model,Aircraft Version,Landing Count,Total Landed Weight
0,200204,ATA Airlines,TZ,ATA Airlines,TZ,Domestic,US,Passenger,Narrow Body,Boeing,757,200,83,16434000
1,200204,ATA Airlines,TZ,ATA Airlines,TZ,Domestic,US,Passenger,Narrow Body,Boeing,757,300,3,672000
2,200204,ATA Airlines,TZ,ATA Airlines,TZ,Domestic,US,Passenger,Wide Body,Lockheed,L1011,0,27,9666000
3,200204,Aeroflot Russian International Airlines,NaN,Aeroflot Russian International Airlines,NaN,International,Europe,Passenger,Wide Body,Boeing,777,0,9,4139946
4,200204,Air Canada,AC,Air Canada,AC,International,Canada,Passenger,Narrow Body,Boeing,737,200,5,525000

In [44]:
# Changing column type to split the values
landings_df['Activity Period'] = landings_df['Activity Period'].astype(str)
landings_df['Year'] = landings_df['Activity Period'].str[0:4]
landings_df['Month'] = landings_df['Activity Period'].str[4:6]

In [45]:
# Changing type back into int
landings_df['Year'] = landings_df['Year'].astype(int)
landings_df['Month'] = landings_df['Month'].astype(int)

In [46]:
#Filtering data
landings_df = landings_df.loc[landings_df['Year'] == 2008]

In [47]:
#Dropping duplicates
landings_df.drop_duplicates(["Year","Operating Airline IATA Code", "GEO Region","Landing Aircraft Type","Aircraft Model"], keep= 'last').head

,Activity Period,Operating Airline,Operating Airline IATA Code,Published Airline,Published Airline IATA Code,GEO Summary,GEO Region,Landing Aircraft Type,Aircraft Body Type,Aircraft Manufacturer,Aircraft Model,Aircraft Version,Landing Count,Total Landed Weight,Year,Month
4210,200801,Air Canada,AC,Air Canada,AC,International,Canada,Passenger,Wide Body,Boeing,767,3Y0,1,199000,2008,1
4216,200801,Air France,AF,Air France,AF,International,Europe,Passenger,Wide Body,Airbus,A330,300,1,401200,2008,1
4347,200802,ATA Airlines,TZ,ATA Airlines,TZ,Domestic,US,Passenger,Narrow Body,Boeing,737,800,1,146300,2008,2
4637,200804,Astar Air Cargo,ER,Astar Air Cargo,ER,Domestic,US,Freighter,Wide Body,McDonnell Douglas,DC-8,73,2,550000,2008,4
4761,200805,American Airlines,AA,American Airlines,AA,Domestic,US,Passenger,Narrow Body,Boeing,737,NaN,1,144000,2008,5
4768,200805,Ameriflight,A8,Ameriflight,A8,Domestic,US,Freighter,Regional Jet,BAE-Avro,BAE-200,NaN,2,25000,2008,5
4913,200806,EVA Airways,BR,EVA Airways,BR,International,Asia,Passenger,Wide Body,Boeing,747,400,30,18900000,2008,6
4919,200806,Federal Express,FX,Federal Express,FX,Domestic,US,Freighter,Wide Body,Airbus,A300,NaN,1,308650,2008,6
5095,200807,SkyWest Airlines,OO,United Airlines - Pre 07/01/2013,UA,Domestic,US,Passenger,Turbo Prop,Embraer,ERJ,120,2154,55573200,2008,7
5156,200808,Alaska Airlines,AS,Alaska Airlines,AS,International,Canada,Passenger,Narrow Body,Boeing,737,700,24,3100800,2008,8
5161,200808,Alaska Airlines,AS,Alaska Airlines,AS,Domestic,US,Passenger,Narrow Body,McDonnell Douglas,MD-80,-,1,130000,2008,8
5170,200808,Ameriflight,A8,Ameriflight,A8,Domestic,US,Freighter,Regional Jet,LearJet,35A,-,1,15300,2008,8
5175,200808,Cargolux Airlines,CV,Cargolux Airlines,CV,International,Europe,Freighter,Wide Body,Boeing,747,400F,1,666000,2008,8
5209,200808,Miami Air International,GL,Miami Air International,GL,Domestic,US,Passenger,Narrow Body,Boeing,737,800,1,146000,2008,8
5212,200808,Midwest Airlines,YX,Midwest Airlines,YX,Domestic,US,Passenger,Narrow Body,McDonnell Douglas,MD-88,-,6,837000,2008,8
5240,200808,TACA,TA,TACA,TA,International,Central America,Passenger,Narrow Body,Airbus,A321,-,4,684640,2008,8
5308,200809,BelAir Airlines,BBB,BelAir Airlines,BBB,International,Europe,Passenger,Wide Body,Boeing,767,300,2,638656,2008,9
5309,200809,BelAir Airlines,BBB,BelAir Airlines,BBB,International,Europe,Passenger,Wide Body,Airbus,A330,200,1,400400,2008,9
5319,200809,Delta Air Lines,DL,Delta Air Lines,DL,Domestic,US,Passenger,Narrow Body,McDonnell Douglas,MD-90,-,2,284000,2008,9
5325,200809,ExpressJet Airlines,XE,Delta Air Lines,DL,Domestic,US,Passenger,Regional Jet,Embraer,ERJ,145XR,3,127647,2008,9
5334,200809,Japan Airlines,JL,Japan Airlines,JL,International,Asia,Freighter,Wide Body,Boeing,747,400F,4,2520000,2008,9
5339,200809,KLM Royal Dutch Airlines,KL,KLM Royal Dutch Airlines,KL,International,Europe,Combi,Wide Body,Boeing,747,400E,30,18843000,2008,9
5349,200809,Midwest Airlines,YX,Midwest Airlines,YX,Domestic,US,Passenger,Narrow Body,McDonnell Douglas,MD-80,-,7,910000,2008,9
5428,200810,Air France,AF,Air France,AF,International,Europe,Passenger,Wide Body,Boeing,747,400,25,14985978,2008,10
5471,200810,KLM Royal Dutch Airlines,KL,KLM Royal Dutch Airlines,KL,International,Europe,Passenger,Wide Body,Boeing,747,400,25,15702500,2008,10
5502,200810,Southern Air,9S,Southern Air,9S,Domestic,US,Freighter,Wide Body,Boeing,747,200F,1,630000,2008,10
5555,200811,Air China,CA,Air China,CA,International,Asia,Passenger,Wide Body,Boeing,747,400M,1,630000,2008,11
5590,200811,EVA Airways,BR,EVA Airways,BR,International,Asia,Freighter,Wide Body,McDonnell Douglas,MD-11,-,1,471500,2008,11
5602,200811,KLM Royal Dutch Airlines,KL,KLM Royal Dutch Airlines,KL,International,Europe,Passenger,Wide Body,Boeing,777,200,8,3759952,2008,11
5628,200811,SkyWest Airlines,OO,United Airlines - Pre 07/01/2013,UA,International,Canada,Passenger,Regional Jet,Bombardier,CL600,2B19,1,47000,2008,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5772,200812,SkyWest Airlines,OO,Delta Air Lines,DL,Domestic,US,Passenger,Regional Jet,Bombardier,CRJ,900,100,7500000,2008,12
5773,200812,SkyWest Airlines,OO,United Airlines - Pre 07/01/2013,UA,Domestic,US,Passenger,Turbo Prop,Embraer,EMB,120,1823,47033400,2008,12
5776,200812,Southwest Airlines,WN,Southwest Airlines,WN,Domestic,US,Passenger,Narrow Body,Boeing,737,700,765,97920000,2008,12
5777,200812,Sun Country Airlines,SY,Sun Country Airlines,SY,Domestic,US,Passenger,Narrow Body,Boeing,737,800,21,3070200,2008,12
5778,200812,TACA,TA,TACA,TA,International,Central America,Passenger,Narrow Body,Airbus,A319,-,2,275000,2008,12
5779,200812,TACA,TA,TACA,TA,International,Central America,Passenger,Narrow Body,Airbus,A320,-,42,5972400,2008,12
5780,200812,US Airways,US,US Airways,US,Domestic,US,Passenger,Narrow Body,Boeing,737,300,32,3648000,2008,12
5783,200812,US Airways,US,US Airways,US,Domestic,US,Passenger,Narrow Body,Airbus,A319,132,217,29880900,2008,12
5786,200812,US Airways,US,US Airways,US,Domestic,US,Passenger,Narrow Body,Airbus,A320,231B,40,5684000,2008,12
5787,200812,US Airways,US,US Airways,US,Domestic,US,Passenger,Narrow Body,Airbus,A321,-,186,31899000,2008,12
5795,200812,United Airlines - Pre 07/01/2013,UA,United Airlines - Pre 07/01/2013,UA,Domestic,US,Passenger,Narrow Body,Boeing,737,522,144,15840000,2008,12
5796,200812,United Airlines - Pre 07/01/2013,UA,United Airlines - Pre 07/01/2013,UA,Domestic,US,Passenger,Wide Body,Boeing,747,422,19,11970000,2008,12
5797,200812,United Airlines - Pre 07/01/2013,UA,United Airlines - Pre 07/01/2013,UA,International,Asia,Passenger,Wide Body,Boeing,747,422,94,59220000,2008,12
5798,200812,United Airlines - Pre 07/01/2013,UA,United Airlines - Pre 07/01/2013,UA,International,Australia / Oceania,Passenger,Wide Body,Boeing,747,422,30,18900000,2008,12
5799,200812,United Airlines - Pre 07/01/2013,UA,United Airlines - Pre 07/01/2013,UA,International,Europe,Passenger,Wide Body,Boeing,747,422,30,18900000,2008,12
5800,200812,United Airlines - Pre 07/01/2013,UA,United Airlines - Pre 07/01/2013,UA,Domestic,US,Passenger,Narrow Body,Boeing,757,-,1059,209682000,2008,12
5801,200812,United Airlines - Pre 07/01/2013,UA,United Airlines - Pre 07/01/2013,UA,International,Mexico,Passenger,Narrow Body,Boeing,757,-,4,792000,2008,12
5803,200812,United Airlines - Pre 07/01/2013,UA,United Airlines - Pre 07/01/2013,UA,Domestic,US,Passenger,Wide Body,Boeing,767,322,52,16640000,2008,12
5805,200812,United Airlines - Pre 07/01/2013,UA,United Airlines - Pre 07/01/2013,UA,Domestic,US,Passenger,Wide Body,Boeing,777,222B,28,12880000,2008,12
5806,200812,United Airlines - Pre 07/01/2013,UA,United Airlines - Pre 07/01/2013,UA,International,Asia,Passenger,Wide Body,Boeing,777,222B,123,56580000,2008,12
5807,200812,United Airlines - Pre 07/01/2013,UA,United Airlines - Pre 07/01/2013,UA,International,Europe,Passenger,Wide Body,Boeing,777,222B,61,28060000,2008,12
5808,200812,United Airlines - Pre 07/01/2013,UA,United Airlines - Pre 07/01/2013,UA,Domestic,US,Passenger,Narrow Body,Airbus,A319,131,623,85841301,2008,12
5809,200812,United Airlines - Pre 07/01/2013,UA,United Airlines - Pre 07/01/2013,UA,International,Canada,Passenger,Narrow Body,Airbus,A319,131,93,12814191,2008,12
5810,200812,United Airlines - Pre 07/01/2013,UA,United Airlines - Pre 07/01/2013,UA,International,Mexico,Passenger,Narrow Body,Airbus,A319,131,16,2204592,2008,12
5811,200812,United Airlines - Pre 07/01/2013,UA,United Airlines - Pre 07/01/2013,UA,International,Canada,Passenger,Narrow Body,Airbus,A320,214,27,3839319,2008,12
5812,200812,United Airlines - Pre 07/01/2013,UA,United Airlines - Pre 07/01/2013,UA,Domestic,US,Passenger,Narrow Body,Airbus,A320,232,809,115038182,2008,12
5813,200812,United Airlines - Pre 07/01/2013,UA,United Airlines - Pre 07/01/2013,UA,International,Mexico,Passenger,Narrow Body,Airbus,A320,232,62,8816276,2008,12
5814,200812,Virgin America,VX,Virgin America,VX,Domestic,US,Passenger,Narrow Body,Airbus,A319,-,266,36654800,2008,12
5815,200812,Virgin America,VX,Virgin America,VX,Domestic,US,Passenger,Narrow Body,Airbus,A320,-,497,70673400,2008,12
5816,200812,Virgin Atlantic,VS,Virgin Atlantic,VS,International,Europe,Passenger,Wide Body,Boeing,747,400,30,18900000,2008,12

In [70]:
#Dropping splited column
landings_df.drop(["Activity Period"], axis=1).head()

,Operating Airline,Operating Airline IATA Code,Published Airline,Published Airline IATA Code,GEO Summary,GEO Region,Landing Aircraft Type,Aircraft Body Type,Aircraft Manufacturer,Aircraft Model,Aircraft Version,Landing Count,Total Landed Weight,Year,Month,ID
4206,ABX Air,GB,ABX Air,GB,Domestic,US,Freighter,Wide Body,Boeing,767,NaN,46,13018000,2008,1,0
4207,ABX Air,GB,ABX Air,GB,Domestic,US,Freighter,Narrow Body,McDonnell Douglas,DC-9,41,22,2244000,2008,1,1
4208,Aer Lingus,EI,Aer Lingus,EI,International,Europe,Passenger,Wide Body,Airbus,A330,200,17,6770000,2008,1,2
4209,Air Canada,AC,Air Canada,AC,International,Canada,Passenger,Wide Body,Boeing,767,233,1,278000,2008,1,3
4210,Air Canada,AC,Air Canada,AC,International,Canada,Passenger,Wide Body,Boeing,767,3Y0,1,199000,2008,1,4
4211,Air Canada,AC,Air Canada,AC,International,Canada,Passenger,Narrow Body,Airbus,A319,114,90,12105000,2008,1,5
4212,Air Canada,AC,Air Canada,AC,International,Canada,Passenger,Narrow Body,Airbus,A320,211,30,4260000,2008,1,6
4213,Air Canada,AC,Air Canada,AC,International,Canada,Passenger,Narrow Body,Airbus,A321,211,13,2229500,2008,1,7
4214,Air Canada,AC,Air Canada,AC,International,Canada,Passenger,Regional Jet,Embraer,ERJ,190,101,9574800,2008,1,8
4215,Air China,CA,Air China,CA,International,Asia,Passenger,Wide Body,Boeing,747,400,31,19530000,2008,1,9
4216,Air France,AF,Air France,AF,International,Europe,Passenger,Wide Body,Airbus,A330,300,1,401200,2008,1,10
4217,Air France,AF,Air France,AF,International,Europe,Passenger,Wide Body,Airbus,A340,300,29,12143700,2008,1,11
4218,Air New Zealand,NZ,Air New Zealand,NZ,International,Australia / Oceania,Passenger,Wide Body,Boeing,777,200,31,14570000,2008,1,12
4219,AirTran Airways,FL,AirTran Airways,FL,Domestic,US,Passenger,Narrow Body,Boeing,737,700,38,4864000,2008,1,13
4220,Alaska Airlines,AS,Alaska Airlines,AS,Domestic,US,Passenger,Narrow Body,Boeing,737,400,246,29766000,2008,1,14
4221,Alaska Airlines,AS,Alaska Airlines,AS,International,Canada,Passenger,Narrow Body,Boeing,737,400,55,6655000,2008,1,15
4222,Alaska Airlines,AS,Alaska Airlines,AS,International,Mexico,Passenger,Narrow Body,Boeing,737,400,33,3993000,2008,1,16
4223,Alaska Airlines,AS,Alaska Airlines,AS,Domestic,US,Passenger,Narrow Body,Boeing,737,700,41,5297200,2008,1,17
4224,Alaska Airlines,AS,Alaska Airlines,AS,International,Canada,Passenger,Narrow Body,Boeing,737,700,24,3100800,2008,1,18
4225,Alaska Airlines,AS,Alaska Airlines,AS,International,Mexico,Passenger,Narrow Body,Boeing,737,700,1,129200,2008,1,19
4226,Alaska Airlines,AS,Alaska Airlines,AS,Domestic,US,Passenger,Narrow Body,Boeing,737,800,67,9648000,2008,1,20
4227,Alaska Airlines,AS,Alaska Airlines,AS,International,Canada,Passenger,Narrow Body,Boeing,737,800,1,144000,2008,1,21
4228,Alaska Airlines,AS,Alaska Airlines,AS,International,Mexico,Passenger,Narrow Body,Boeing,737,800,62,8928000,2008,1,22
4229,Alaska Airlines,AS,Alaska Airlines,AS,Domestic,US,Passenger,Narrow Body,Boeing,737,900,34,4974200,2008,1,23
4230,Alaska Airlines,AS,Alaska Airlines,AS,International,Canada,Passenger,Narrow Body,Boeing,737,900,1,146300,2008,1,24
4231,Alaska Airlines,AS,Alaska Airlines,AS,International,Mexico,Passenger,Narrow Body,Boeing,737,900,27,3950100,2008,1,25
4232,Alaska Airlines,AS,Alaska Airlines,AS,Domestic,US,Passenger,Narrow Body,McDonnell Douglas,MD-80,NaN,23,2990000,2008,1,26
4233,All Nippon Airways,NH,All Nippon Airways,NH,International,Asia,Passenger,Wide Body,Boeing,777,300ER,31,17174000,2008,1,27
4234,American Airlines,AA,American Airlines,AA,Domestic,US,Passenger,Narrow Body,Boeing,757,NaN,231,45738000,2008,1,28
4235,American Airlines,AA,American Airlines,AA,Domestic,US,Passenger,Wide Body,Boeing,767,200,78,21060000,2008,1,29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5787,US Airways,US,US Airways,US,Domestic,US,Passenger,Narrow Body,Airbus,A321,-,186,31899000,2008,12,1581
5788,United Airlines,UA,United Airlines,UA,Domestic,US,Passenger,Narrow Body,Boeing,737,300,8,912000,2008,12,1582
5789,United Airlines,UA,United Airlines,UA,Domestic,US,Passenger,Narrow Body,Boeing,737,700,12,1536000,2008,12,1583
5790,United Airlines,UA,United Airlines,UA,Domestic,US,Passenger,Narrow Body,Boeing,737,800,239,34416000,2008,12,1584
5791,United Airlines,UA,United Airlines,UA,Domestic,US,Passenger,Narrow Body,Boeing,737,900,48,7070400,2008,12,1585
5792,United Airlines,UA,United Airlines,UA,Domestic,US,Passenger,Narrow Body,Boeing,757,200,31,6138000,2008,12,1586
5793,United Airlines,UA,United Airlines,UA,Domestic,US,Passenger,Narrow Body,Boeing,757,300,46,10304000,2008,12,1587
5794,United Airlines - Pre 07/01/2013,UA,United Airlines - Pre 07/01/2013,UA,Domestic,US,Passenger,Narrow Body,Boeing,737,322,257,29298000,2008,12,1588
5795,United Airlines - Pre 07/01/2013,UA,United Airlines - Pre 07/01/2013,UA,Domestic,US,Passenger,Narrow Body,Boeing,737,522,144,15840000,2008,12,1589
5796,United Airlines - Pre 07/01/2013,UA,United Airlines - Pre 07/01/2013,UA,Domestic,US,Passenger,Wide Body,Boeing,747,422,19,11970000,2008,12,1590
5797,United Airlines - Pre 07/01/2013,UA,United Airlines - Pre 07/01/2013,UA,International,Asia,Passenger,Wide Body,Boeing,747,422,94,59220000,2008,12,1591
5798,United Airlines - Pre 07/01/2013,UA,United Airlines - Pre 07/01/2013,UA,International,Australia / Oceania,Passenger,Wide Body,Boeing,747,422,30,18900000,2008,12,1592
5799,United Airlines - Pre 07/01/2013,UA,United Airlines - Pre 07/01/2013,UA,International,Europe,Passenger,Wide Body,Boeing,747,422,30,18900000,2008,12,1593
5800,United Airlines - Pre 07/01/2013,UA,United Airlines - Pre 07/01/2013,UA,Domestic,US,Passenger,Narrow Body,Boeing,757,-,1059,209682000,2008,12,1594
5801,United Airlines - Pre 07/01/2013,UA,United Airlines - Pre 07/01/2013,UA,International,Mexico,Passenger,Narrow Body,Boeing,757,-,4,792000,2008,12,1595
5802,United Airlines - Pre 07/01/2013,UA,United Airlines - Pre 07/01/2013,UA,Domestic,US,Passenger,Wide Body,Boeing,767,300,187,56100000,2008,12,1596
5803,United Airlines - Pre 07/01/2013,UA,United Airlines - Pre 07/01/2013,UA,Domestic,US,Passenger,Wide Body,Boeing,767,322,52,16640000,2008,12,1597
5804,United Airlines - Pre 07/01/2013,UA,United Airlines - Pre 07/01/2013,UA,Domestic,US,Passenger,Wide Body,Boeing,777,222,127,56515000,2008,12,1598
5805,United Airlines - Pre 07/01/2013,UA,United Airlines - Pre 07/01/2013,UA,Domestic,US,Passenger,Wide Body,Boeing,777,222B,28,12880000,2008,12,1599
5806,United Airlines - Pre 07/01/2013,UA,United Airlines - Pre 07/01/2013,UA,International,Asia,Passenger,Wide Body,Boeing,777,222B,123,56580000,2008,12,1600
5807,United Airlines - Pre 07/01/2013,UA,United Airlines - Pre 07/01/2013,UA,International,Europe,Passenger,Wide Body,Boeing,777,222B,61,28060000,2008,12,1601
5808,United Airlines - Pre 07/01/2013,UA,United Airlines - Pre 07/01/2013,UA,Domestic,US,Passenger,Narrow Body,Airbus,A319,131,623,85841301,2008,12,1602
5809,United Airlines - Pre 07/01/2013,UA,United Airlines - Pre 07/01/2013,UA,International,Canada,Passenger,Narrow Body,Airbus,A319,131,93,12814191,2008,12,1603
5810,United Airlines - Pre 07/01/2013,UA,United Airlines - Pre 07/01/2013,UA,International,Mexico,Passenger,Narrow Body,Airbus,A319,131,16,2204592,2008,12,1604
5811,United Airlines - Pre 07/01/2013,UA,United Airlines - Pre 07/01/2013,UA,International,Canada,Passenger,Narrow Body,Airbus,A320,214,27,3839319,2008,12,1605
5812,United Airlines - Pre 07/01/2013,UA,United Airlines - Pre 07/01/2013,UA,Domestic,US,Passenger,Narrow Body,Airbus,A320,232,809,115038182,2008,12,1606
5813,United Airlines - Pre 07/01/2013,UA,United Airlines - Pre 07/01/2013,UA,International,Mexico,Passenger,Narrow Body,Airbus,A320,232,62,8816276,2008,12,1607
5814,Virgin America,VX,Virgin America,VX,Domestic,US,Passenger,Narrow Body,Airbus,A319,-,266,36654800,2008,12,1608
5815,Virgin America,VX,Virgin America,VX,Domestic,US,Passenger,Narrow Body,Airbus,A320,-,497,70673400,2008,12,1609
5816,Virgin Atlantic,VS,Virgin Atlantic,VS,International,Europe,Passenger,Wide Body,Boeing,747,400,30,18900000,2008,12,1610

In [71]:
#Creating column to set as 'id'
landings_df['ID'] = range(0, 0+len(landings_df))

In [55]:
# Create a filtered dataframe from specific columns
landings_cols = ["ID","Operating Airline IATA Code","Year", "Month", "GEO Region", 
                 "Landing Aircraft Type", "Aircraft Manufacturer", "Aircraft Model"]
landings_transformed = landings_df[landings_cols].copy()

# Rename the column headers
landings_transformed = landings_transformed.rename(columns={"ID":"id",
                                                            "Operating Airline IATA Code": "unique_carrier",
                                                          "Year": "year",
                                                          "Month": "month",
                                                     "GEO Region": "geo_region",
                                                     "Landing Aircraft Type": "aircraft_type",
                                                           "Aircraft Manufacturer": "aircraft_manufacturer",
                                                     "Aircraft Model": "aircraft_Model"})

#landings_transformed.drop_duplicates(["unique_carrier","geo_region"], keep= 'last')
landings_transformed.drop_duplicates("id", inplace=True)
landings_transformed.set_index("id", inplace=True)
landings_transformed.tail()

,unique_carrier,year,month,geo_region,aircraft_type,aircraft_manufacturer,aircraft_Model
id,,,,,,,
1606,UA,2008,12,US,Passenger,Airbus,A320
1607,UA,2008,12,Mexico,Passenger,Airbus,A320
1608,VX,2008,12,US,Passenger,Airbus,A319
1609,VX,2008,12,US,Passenger,Airbus,A320
1610,VS,2008,12,Europe,Passenger,Boeing,747

### Transform Passenger DataFrame

In [1]:
#importing files 
passenger_file = "Resources/air-traffic-passenger-statistics.csv"
passenger_df = pd.read_csv(passenger_file)
passenger_df.head()

NameError: name 'pd' is not defined

In [57]:
# Changing column type to split the values
passenger_df['Activity Period'] = passenger_df['Activity Period'].astype(str)
passenger_df['Year'] = passenger_df['Activity Period'].str[0:4]
passenger_df['Month'] = passenger_df['Activity Period'].str[4:6]

In [58]:
# Changing type back into int
passenger_df['Year'] = passenger_df['Year'].astype(int)
passenger_df['Month'] = passenger_df['Month'].astype(int)

In [63]:
#Filtering data
passenger_df = passenger_df.loc[passenger_df['Year'] == 2008]
passenger_df.head()

,Activity Period,Operating Airline,Operating Airline IATA Code,Published Airline,Published Airline IATA Code,GEO Summary,GEO Region,Activity Type Code,Price Category Code,Terminal,Boarding Area,Passenger Count,Year,Month
3473,200801,Aer Lingus,EI,Aer Lingus,EI,International,Europe,Deplaned,Other,International,A,2858,2008,1
3474,200801,Aer Lingus,EI,Aer Lingus,EI,International,Europe,Enplaned,Other,International,A,2716,2008,1
3475,200801,Air Canada,AC,Air Canada,AC,International,Canada,Deplaned,Other,Terminal 3,E,19756,2008,1
3476,200801,Air Canada,AC,Air Canada,AC,International,Canada,Enplaned,Other,Terminal 3,E,18129,2008,1
3477,200801,Air China,CA,Air China,CA,International,Asia,Deplaned,Other,International,G,7603,2008,1

In [64]:
#Dropping duplicates
passenger_df.drop_duplicates(["Year","Operating Airline IATA Code", "GEO Region",
                              "Terminal","Boarding Area", "Passenger Count"], keep= 'last'.head()

,Activity Period,Operating Airline,Operating Airline IATA Code,Published Airline,Published Airline IATA Code,GEO Summary,GEO Region,Activity Type Code,Price Category Code,Terminal,Boarding Area,Passenger Count,Year,Month
3473,200801,Aer Lingus,EI,Aer Lingus,EI,International,Europe,Deplaned,Other,International,A,2858,2008,1
3474,200801,Aer Lingus,EI,Aer Lingus,EI,International,Europe,Enplaned,Other,International,A,2716,2008,1
3475,200801,Air Canada,AC,Air Canada,AC,International,Canada,Deplaned,Other,Terminal 3,E,19756,2008,1
3476,200801,Air Canada,AC,Air Canada,AC,International,Canada,Enplaned,Other,Terminal 3,E,18129,2008,1
3477,200801,Air China,CA,Air China,CA,International,Asia,Deplaned,Other,International,G,7603,2008,1
3478,200801,Air China,CA,Air China,CA,International,Asia,Enplaned,Other,International,G,6027,2008,1
3479,200801,Air France,AF,Air France,AF,International,Europe,Deplaned,Other,International,A,6827,2008,1
3480,200801,Air France,AF,Air France,AF,International,Europe,Enplaned,Other,International,A,6190,2008,1
3481,200801,Air New Zealand,NZ,Air New Zealand,NZ,International,Australia / Oceania,Deplaned,Other,International,G,8057,2008,1
3482,200801,Air New Zealand,NZ,Air New Zealand,NZ,International,Australia / Oceania,Enplaned,Other,International,G,8977,2008,1
3483,200801,AirTran Airways,FL,AirTran Airways,FL,Domestic,US,Deplaned,Low Fare,Terminal 1,B,4463,2008,1
3484,200801,AirTran Airways,FL,AirTran Airways,FL,Domestic,US,Enplaned,Low Fare,Terminal 1,B,4365,2008,1
3485,200801,Alaska Airlines,AS,Alaska Airlines,AS,Domestic,US,Deplaned,Other,Terminal 1,B,30390,2008,1
3486,200801,Alaska Airlines,AS,Alaska Airlines,AS,Domestic,US,Enplaned,Other,Terminal 1,B,32299,2008,1
3487,200801,Alaska Airlines,AS,Alaska Airlines,AS,Domestic,US,Thru / Transit,Other,Terminal 1,B,1482,2008,1
3488,200801,Alaska Airlines,AS,Alaska Airlines,AS,International,Canada,Deplaned,Other,Terminal 1,B,6498,2008,1
3489,200801,Alaska Airlines,AS,Alaska Airlines,AS,International,Canada,Enplaned,Other,Terminal 1,B,7566,2008,1
3490,200801,Alaska Airlines,AS,Alaska Airlines,AS,International,Canada,Thru / Transit,Other,Terminal 1,B,253,2008,1
3491,200801,Alaska Airlines,AS,Alaska Airlines,AS,International,Mexico,Deplaned,Other,International,A,12421,2008,1
3492,200801,Alaska Airlines,AS,Alaska Airlines,AS,International,Mexico,Enplaned,Other,International,A,11883,2008,1
3493,200801,Alaska Airlines,AS,Alaska Airlines,AS,International,Mexico,Thru / Transit,Other,International,A,1682,2008,1
3494,200801,All Nippon Airways,NH,All Nippon Airways,NH,International,Asia,Deplaned,Other,International,G,6541,2008,1
3495,200801,All Nippon Airways,NH,All Nippon Airways,NH,International,Asia,Enplaned,Other,International,G,5456,2008,1
3496,200801,American Airlines,AA,American Airlines,AA,Domestic,US,Deplaned,Other,Terminal 3,E,125541,2008,1
3497,200801,American Airlines,AA,American Airlines,AA,Domestic,US,Enplaned,Other,Terminal 3,E,117928,2008,1
3498,200801,American Eagle Airlines,MQ,American Airlines,AA,Domestic,US,Deplaned,Other,Terminal 3,E,3209,2008,1
3499,200801,American Eagle Airlines,MQ,American Airlines,AA,Domestic,US,Enplaned,Other,Terminal 3,E,2961,2008,1
3501,200801,Ameriflight,A8,Ameriflight,A8,Domestic,US,Enplaned,Other,Other,Other,2,2008,1
3502,200801,Asiana Airlines,OZ,Asiana Airlines,OZ,International,Asia,Deplaned,Other,International,A,4890,2008,1
3503,200801,Asiana Airlines,OZ,Asiana Airlines,OZ,International,Asia,Enplaned,Other,International,A,4181,2008,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4876,200812,United Airlines,UA,United Airlines,UA,Domestic,US,Deplaned,Other,Terminal 1,B,57225,2008,12
4877,200812,United Airlines,UA,United Airlines,UA,Domestic,US,Enplaned,Other,Terminal 1,B,56970,2008,12
4878,200812,United Airlines - Pre 07/01/2013,UA,United Airlines - Pre 07/01/2013,UA,Domestic,US,Deplaned,Other,International,G,12419,2008,12
4879,200812,United Airlines - Pre 07/01/2013,UA,United Airlines - Pre 07/01/2013,UA,Domestic,US,Enplaned,Other,International,G,5251,2008,12
4880,200812,United Airlines - Pre 07/01/2013,UA,United Airlines - Pre 07/01/2013,UA,Domestic,US,Deplaned,Other,Terminal 3,E,19182,2008,12
4881,200812,United Airlines - Pre 07/01/2013,UA,United Airlines - Pre 07/01/2013,UA,Domestic,US,Enplaned,Other,Terminal 3,E,19189,2008,12
4882,200812,United Airlines - Pre 07/01/2013,UA,United Airlines - Pre 07/01/2013,UA,Domestic,US,Thru / Transit,Other,Terminal 3,E,197,2008,12
4883,200812,United Airlines - Pre 07/01/2013,UA,United Airlines - Pre 07/01/2013,UA,Domestic,US,Deplaned,Low Fare,Terminal 3,F,38186,2008,12
4884,200812,United Airlines - Pre 07/01/2013,UA,United Airlines - Pre 07/01/2013,UA,Domestic,US,Deplaned,Other,Terminal 3,F,326272,2008,12
4885,200812,United Airlines - Pre 07/01/2013,UA,United Airlines - Pre 07/01/2013,UA,Domestic,US,Enplaned,Low Fare,Terminal 3,F,43928,2008,12
4886,200812,United Airlines - Pre 07/01/2013,UA,United Airlines - Pre 07/01/2013,UA,Domestic,US,Enplaned,Other,Terminal 3,F,320658,2008,12
4887,200812,United Airlines - Pre 07/01/2013,UA,United Airlines - Pre 07/01/2013,UA,Domestic,US,Thru / Transit,Other,Terminal 3,F,3753,2008,12
4888,200812,United Airlines - Pre 07/01/2013,UA,United Airlines - Pre 07/01/2013,UA,International,Asia,Deplaned,Other,International,G,55453,2008,12
4889,200812,United Airlines - Pre 07/01/2013,UA,United Airlines - Pre 07/01/2013,UA,International,Asia,Enplaned,Other,International,G,61687,2008,12
4890,200812,United Airlines - Pre 07/01/2013,UA,United Airlines - Pre 07/01/2013,UA,International,Asia,Thru / Transit,Other,International,G,2113,2008,12
4891,200812,United Airlines - Pre 07/01/2013,UA,United Airlines - Pre 07/01/2013,UA,International,Australia / Oceania,Deplaned,Other,International,G,8173,2008,12
4892,200812,United Airlines - Pre 07/01/2013,UA,United Airlines - Pre 07/01/2013,UA,International,Australia / Oceania,Enplaned,Other,International,G,8428,2008,12
4893,200812,United Airlines - Pre 07/01/2013,UA,United Airlines - Pre 07/01/2013,UA,International,Australia / Oceania,Thru / Transit,Other,International,G,243,2008,12
4894,200812,United Airlines - Pre 07/01/2013,UA,United Airlines - Pre 07/01/2013,UA,International,Canada,Deplaned,Other,Terminal 3,F,11873,2008,12
4895,200812,United Airlines - Pre 07/01/2013,UA,United Airlines - Pre 07/01/2013,UA,International,Canada,Enplaned,Other,Terminal 3,F,12309,2008,12
4896,200812,United Airlines - Pre 07/01/2013,UA,United Airlines - Pre 07/01/2013,UA,International,Europe,Deplaned,Other,International,G,23520,2008,12
4897,200812,United Airlines - Pre 07/01/2013,UA,United Airlines - Pre 07/01/2013,UA,International,Europe,Enplaned,Other,International,G,22343,2008,12
4898,200812,United Airlines - Pre 07/01/2013,UA,United Airlines - Pre 07/01/2013,UA,International,Europe,Thru / Transit,Other,International,G,409,2008,12
4899,200812,United Airlines - Pre 07/01/2013,UA,United Airlines - Pre 07/01/2013,UA,International,Mexico,Deplaned,Other,International,G,9509,2008,12
4900,200812,United Airlines - Pre 07/01/2013,UA,United Airlines - Pre 07/01/2013,UA,International,Mexico,Enplaned,Other,International,G,11038,2008,12
4901,200812,United Airlines - Pre 07/01/2013,UA,United Airlines - Pre 07/01/2013,UA,International,Mexico,Thru / Transit,Other,International,G,71,2008,12
4902,200812,Virgin America,VX,Virgin America,VX,Domestic,US,Deplaned,Low Fare,International,A,85284,2008,12
4903,200812,Virgin America,VX,Virgin America,VX,Domestic,US,Enplaned,Low Fare,International,A,86713,2008,12
4904,200812,Virgin Atlantic,VS,Virgin Atlantic,VS,International,Europe,Deplaned,Other,International,A,8987,2008,12
4905,200812,Virgin Atlantic,VS,Virgin Atlantic,VS,International,Europe,Enplaned,Other,International,A,8447,2008,12

In [68]:
#Creating column to set as 'id'
passenger_df['ID'] = range(0, 0+len(passenger_df))

In [74]:
#Dropping splited column
passenger_df.drop(["Activity Period"], axis=1).head()

,Operating Airline,Operating Airline IATA Code,Published Airline,Published Airline IATA Code,GEO Summary,GEO Region,Activity Type Code,Price Category Code,Terminal,Boarding Area,Passenger Count,Year,Month,ID
3473,Aer Lingus,EI,Aer Lingus,EI,International,Europe,Deplaned,Other,International,A,2858,2008,1,0
3474,Aer Lingus,EI,Aer Lingus,EI,International,Europe,Enplaned,Other,International,A,2716,2008,1,1
3475,Air Canada,AC,Air Canada,AC,International,Canada,Deplaned,Other,Terminal 3,E,19756,2008,1,2
3476,Air Canada,AC,Air Canada,AC,International,Canada,Enplaned,Other,Terminal 3,E,18129,2008,1,3
3477,Air China,CA,Air China,CA,International,Asia,Deplaned,Other,International,G,7603,2008,1,4

In [75]:
# Create a filtered dataframe from specific columns
passenger_cols = ["ID","Operating Airline IATA Code","Year", "Month", "GEO Region", 
                 "Terminal", "Boarding Area", "Passenger Count"]
passenger_transformed = passenger_df[passenger_cols].copy()

# Rename the column headers
passenger_transformed = passenger_transformed.rename(columns={"ID":"id",
                                                            "Operating Airline IATA Code": "unique_carrier",
                                                          "Year": "year",
                                                          "Month": "month",
                                                     "GEO Region": "geo_region",
                                                     "Terminal": "terminal",
                                                           "Boarding Area": "boarding_area",
                                                     "Passenger Count": "passengers_number"})

#landings_transformed.drop_duplicates(["unique_carrier","geo_region"], keep= 'last')
passenger_transformed.drop_duplicates("id", inplace=True)
passenger_transformed.set_index("id", inplace=True)
passenger_transformed.tail()

,unique_carrier,year,month,geo_region,terminal,boarding_area,passengers_number
id,,,,,,,
1428,UA,2008,12,Mexico,International,G,71
1429,VX,2008,12,US,International,A,85284
1430,VX,2008,12,US,International,A,86713
1431,VS,2008,12,Europe,International,A,8987
1432,VS,2008,12,Europe,International,A,8447

In [78]:
connection_string = "root:<insert your password>@localhost/sfo_db"
engine = create_engine(f'mysql://{connection_string}')

In [79]:
# Confirm tables
engine.table_names()

['delays', 'landings', 'passengers']

In [80]:
delay_transformed.to_sql(name='delays', con=engine, if_exists='append', index=True)

In [81]:
landings_transformed.to_sql(name='landings', con=engine, if_exists='append', index=True)

In [82]:
passenger_transformed.to_sql(name='passengers', con=engine, if_exists='append', index=True)